from .db import Database, prepare_database


def main(clean):
    prepare_database(clean=clean)

    with Database() as db:
        ...


def options():
    def booking():
        book_a_table = ...
        change_booking = ...
        cancel_booking = ...
        show_all_bookings = ...
        show_tables_for_date = ...

    def menu():
        add_item_to_menu = ...

    def order():
        show_menu = ...
        order_from_menu = ...
        pay_order = ...

    def kitchen():
        show_orders = ...
        update_order_status = ...


# ENDFILE
